In [1]:

import torch
import numpy as np
import sys
sys.path.append("..")
import d2lzh_pytorch as d2l


ModuleNotFoundError: No module named 'd2lzh_pytorch'

In [3]:
import torch 

In [7]:
x = torch.empty(5,3)
print(x)

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 1.1351e-43, 0.0000e+00],
        [1.2152e-03, 3.0928e-41, 1.3111e-02]])


In [9]:
x = torch.rand(5,3)
print(x)

tensor([[0.3441, 0.9036, 0.2480],
        [0.7105, 0.5797, 0.9290],
        [0.0609, 0.9829, 0.4345],
        [0.6143, 0.4709, 0.6051],
        [0.8542, 0.5863, 0.4148]])


In [10]:
x = torch.zeros(5,3,dtype = torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [12]:
x = torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [14]:
x = x.new_ones(5,3,dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [16]:
x = torch.randn_like(x, dtype=torch.float) #指定新的数据类型
print(x)

tensor([[ 0.1539, -0.5260, -0.9908],
        [-0.6833,  1.4780, -0.5737],
        [-1.3103, -1.3608, -0.4864],
        [ 0.9470,  1.2774, -1.1921],
        [ 0.6021,  1.8337, -0.9034]])


In [17]:
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


In [18]:
# 2.2.2 
y = torch.rand(5,3)
print(x+y)

tensor([[ 1.1372,  0.2596, -0.0684],
        [ 0.2766,  1.6033, -0.3890],
        [-0.3962, -0.8181, -0.0934],
        [ 1.8023,  1.9766, -1.0250],
        [ 0.9791,  2.6753, -0.1576]])


In [19]:
print(torch.add(x,y))

tensor([[ 1.1372,  0.2596, -0.0684],
        [ 0.2766,  1.6033, -0.3890],
        [-0.3962, -0.8181, -0.0934],
        [ 1.8023,  1.9766, -1.0250],
        [ 0.9791,  2.6753, -0.1576]])


In [25]:
result = torch.empty(5,3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.3078, -1.0520, -1.9817],
        [-0.5294,  0.9521, -1.5645],
        [-1.1564, -1.8868, -1.4772],
        [ 1.1009,  0.7514, -2.1829],
        [ 0.7560,  1.3077, -1.8942]])


In [33]:
x

tensor([[ 2.1539,  1.4740,  1.0092],
        [-0.6833,  1.4780, -0.5737],
        [-1.3103, -1.3608, -0.4864],
        [ 0.9470,  1.2774, -1.1921],
        [ 0.6021,  1.8337, -0.9034]])

In [32]:
y = x[0, :]
y

tensor([2.1539, 1.4740, 1.0092])

In [43]:
y = x.view(15)
x
z = x.view(-1,5)
print (x.size(),y.size(),z.size())
# -1代表自适应

torch.Size([5, 3]) torch.Size([15]) torch.Size([3, 5])


In [41]:
z

tensor([[ 2.1539,  1.4740,  1.0092, -0.6833,  1.4780],
        [-0.5737, -1.3103, -1.3608, -0.4864,  0.9470],
        [ 1.2774, -1.1921,  0.6021,  1.8337, -0.9034]])

In [44]:
x

tensor([[ 2.1539,  1.4740,  1.0092],
        [-0.6833,  1.4780, -0.5737],
        [-1.3103, -1.3608, -0.4864],
        [ 0.9470,  1.2774, -1.1921],
        [ 0.6021,  1.8337, -0.9034]])